post: A journey through your code
sinnerschrader/s2engineers-content pull request #32
Opened 2020-11-02 15:55 UTC by tobiastimm

This is a repost, of my own original post.
https://dev.to/tobiastimm/onboard-your-codebase-with-codetour-2jc8

I can take my own post down if this gets published :)

2020-11-02 17:26 UTC, kotzendekrabbe requested changes

2020-11-02 17:26 UTC, kotzendekrabbe commented on posts/tobi/a-journey-through-your-code.md
> +tags: 'onboarding, vscode, resource, codenewbie'
recommendation for hashtags on the existing and moderate hashtags of dev.to

resource -> productivity

2020-11-02 17:26 UTC, kotzendekrabbe commented on posts/tobi/a-journey-through-your-code.md
> +cover_image: posts/assets/000_cover.jpg
delete the cover_image if you don't need it

2020-11-02 17:26 UTC, kotzendekrabbe commented on posts/tobi/a-journey-through-your-code.md
> +---
great one - and something new I learned :) thank you

2020-11-03 11:29 UTC, tobiastimm commented on posts/tobi/a-journey-through-your-code.md
> +cover_image: posts/assets/000_cover.jpg
fixed

2020-11-03 11:29 UTC, tobiastimm commented on posts/tobi/a-journey-through-your-code.md
> +tags: 'onboarding, vscode, resource, codenewbie'
changed! ty

2020-11-03 11:29 UTC, tobiastimm commented on posts/tobi/a-journey-through-your-code.md
> +---
Fixed your comments 👍

2020-11-11 18:57 UTC, kotzendekrabbe approved these changes

2020-11-17 08:07 UTC, merged